# Lab 4

In [0]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train],\
                                feed_dict = {x1:x1_data,\
                                            x2:x2_data,\
                                            x3:x3_data,\
                                            Y:y_data})
  if step % 200 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
                               

0 Cost:  8675.263 
Prediction:
 [72.8454   82.51077  83.85051  91.992966 61.101097]
200 Cost:  10.511826 
Prediction:
 [155.19043 181.9444  181.58499 198.4419  137.04333]
400 Cost:  9.520312 
Prediction:
 [154.95967 182.10344 181.51537 198.38316 137.25911]
600 Cost:  8.629985 
Prediction:
 [154.74127 182.25401 181.44952 198.32721 137.46371]
800 Cost:  7.8304152 
Prediction:
 [154.53458 182.39655 181.38727 198.2739  137.65778]
1000 Cost:  7.1122575 
Prediction:
 [154.33893 182.5315  181.32837 198.22305 137.8418 ]
1200 Cost:  6.467256 
Prediction:
 [154.15382 182.65923 181.2727  198.1746  138.01636]
1400 Cost:  5.88787 
Prediction:
 [153.97867 182.78012 181.22006 198.12839 138.18192]
1600 Cost:  5.3673086 
Prediction:
 [153.8129  182.89458 181.1703  198.08427 138.33894]
1800 Cost:  4.899586 
Prediction:
 [153.6561  183.00293 181.12332 198.0422  138.48795]
2000 Cost:  4.4792795 
Prediction:
 [153.50769 183.10544 181.07886 198.00201 138.62926]


In [0]:
import tensorflow as tf

x_data = [[73., 80., 75.],\
          [93., 88., 93.],\
          [89., 91., 90.],\
          [96., 98., 100.],\
          [73., 66., 70]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train],\
                                feed_dict = {X:x_data,\
                                            Y:y_data})
  if step % 200 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
                               

0 Cost:  1653.2445 
Prediction:
 [[126.26988]
 [134.91422]
 [141.65134]
 [154.7664 ]
 [ 98.12782]]
200 Cost:  56.32259 
Prediction:
 [[161.0711 ]
 [177.8515 ]
 [183.3823 ]
 [200.26419]
 [131.10947]]
400 Cost:  50.68458 
Prediction:
 [[160.51544]
 [178.23358]
 [183.21349]
 [200.13081]
 [131.62042]]
600 Cost:  45.624672 
Prediction:
 [[159.98935]
 [178.59538]
 [183.05373]
 [200.00401]
 [132.10469]]
800 Cost:  41.08317 
Prediction:
 [[159.49123]
 [178.93797]
 [182.90253]
 [199.88345]
 [132.56372]]
1000 Cost:  37.007076 
Prediction:
 [[159.01965]
 [179.26239]
 [182.75946]
 [199.76884]
 [132.99884]]
1200 Cost:  33.34855 
Prediction:
 [[158.5732 ]
 [179.56956]
 [182.62408]
 [199.65987]
 [133.4113 ]]
1400 Cost:  30.06459 
Prediction:
 [[158.15053]
 [179.86044]
 [182.49599]
 [199.5562 ]
 [133.80229]]
1600 Cost:  27.11683 
Prediction:
 [[157.7504 ]
 [180.13585]
 [182.3748 ]
 [199.45758]
 [134.17296]]
1800 Cost:  24.470722 
Prediction:
 [[157.37163]
 [180.39664]
 [182.26015]
 [199.36377]
 [134.5

### 구글 colab에 파일 업로드 기능

In [0]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving data-01-test-score.csv to data-01-test-score.csv
User uploaded file "data-01-test-score.csv" with length 653 bytes


In [0]:
import numpy as np

In [0]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [0]:
print(x_data.shape, len(x_data))
print(y_data.shape)

(25, 3) 25
(25, 1)


In [0]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
  sess.run([cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})

print("Your score will be ", sess.run(hypothesis, \
                                      feed_dict = {X:[[100, 70, 101]]}))  
print("Your score will be ", sess.run(hypothesis, \
                                      feed_dict = {X:[[60, 70, 119], \
                                                      [90, 100, 80]]}))  

Your score will be  [[184.61107]]
Your score will be  [[139.78151]
 [187.86345]]
